server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/xiti?characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/xiti?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

    username: root
    password: root

mybatis:
    typeAliasesPackage: com.yuntu.demo.pojo
#    mapperLocations: classpath:mapper/*.xml